services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
      - node_modules_cache:/workspace/node_modules
      - gem_cache:/workspace/vendor/bundle
    ports:
      - '4567:4567'
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: template-sinatra_development
    tty: true
    stdin_open: true
    command: ['sleep', 'infinity']

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  node_modules_cache:
  gem_cache:
  db_data:
