default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  port: 3306
  host: <%= ENV.fetch('DATABASE_HOST') %>
  username: <%= ENV.fetch('DATABASE_USER') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>

development:
  <<: *default
  database: template-sinatra_development

test:
  <<: *default
  database: template-sinatra_test

production:
  <<: *default
  database: template-sinatra_production
