# frozen_string_literal: true

# This file is auto-generated by Sequel
# To regenerate it, run the schema generation script

Sequel::Schema.define do
  create_table :users do
    column :id, :integer, null: false
    column :name, :string, null: false
    column :email, :string, null: false
    column :created_at, :datetime, null: true, default: 'CURRENT_TIMESTAMP'
    column :updated_at, :datetime, null: true, default: 'CURRENT_TIMESTAMP'
  end
end
