# frozen_string_literal: true

require 'yaml'
require 'sequel'

def create_database(client)
  database_name = ENV['DATABASE_NAME']
  databases = client.fetch("SHOW DATABASES LIKE '#{database_name}'").all
  if databases.any?
    puts "Database '#{database_name}' already exists."
  else
    client.run("CREATE DATABASE `#{database_name}`")
    puts "Database '#{database_name}' created successfully!"
  end
end

def create_table(client)
  if client.table_exists?(:users)
    puts "Table 'users' already exists."
  else
    create_users_table_sql(client)
    puts "Table 'users' created successfully!"
  end
end

def create_users_table_sql(client)
  client.create_table?(:users) do
    primary_key :id
    String :name, null: false
    String :email, null: false, unique: true
    DateTime :created_at, default: Sequel::CURRENT_TIMESTAMP
    DateTime :updated_at, default: Sequel::CURRENT_TIMESTAMP
  end
end

def create_users_seed_data(client)
  user_count = client[:users].count

  if user_count.zero?
    users = YAML.load_file(File.join(File.dirname(__FILE__), 'seeds/users.yml'))
    insert_users(client, users)
    puts 'users data inserted successfully!'
  else
    puts 'users data already exists. No data inserted.'
  end
end

def insert_users(client, users)
  users.each do |user|
    puts "Inserting user: #{user.inspect}"
    client[:users].insert(name: user['name'], email: user['email'])
  end
end

def drop_database(client)
  database_name = ENV['DATABASE_NAME']
  databases = client.fetch("SHOW DATABASES LIKE '#{database_name}'").all
  if databases.any?
    client.run("DROP DATABASE `#{database_name}`")
    puts "Database '#{database_name}' dropped successfully!"
  else
    puts "Database '#{database_name}' does not exist."
  end
end

def generate_schema(client)
  File.open('db/schema.rb', 'w') do |file|
    write_schema_header(file)
    write_tables_schema(client, file)
    file.puts 'end'
  end
end

def write_schema_header(file)
  file.puts '# frozen_string_literal: true'
  file.puts ''
  file.puts '# This file is auto-generated by Sequel'
  file.puts '# To regenerate it, run the schema generation script'
  file.puts "\nSequel::Schema.define do\n"
end

def write_tables_schema(client, file)
  client.tables.each do |table|
    columns = client.schema(table)
    write_table_definition(file, table, columns)
  end
end

def write_table_definition(file, table, columns)
  file.puts "  create_table :#{table} do"
  columns.each do |column, attributes|
    write_column_definition(file, column, attributes)
  end
  file.puts '  end'
end

def write_column_definition(file, column, attributes)
  type = attributes[:type]
  options = []
  options << "null: #{attributes[:allow_null]}" unless attributes[:allow_null].nil?
  options << "default: '#{attributes[:default]}'" unless attributes[:default].nil?
  file.puts "    column :#{column}, :#{type}#{options.any? ? ", #{options.join(', ')}" : ''}"
end
