name: Static Analysis

on:
  pull_request:
    paths: '.github/workflows/*.yml'
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker run --rm -v "$(pwd):/$(pwd)" -w "$(pwd)" rhysd/actionlint:latest
